language: python
services:
  - docker

install:
  - make deps
#  - pip install --upgrade pytest
#  - pip install -r test_requirements.txt

script:
  - make lint
  - make test
  - make test_cov
  - make test_xunit
  - make docker_build
  - make docker_push

deploy:
 provider: heroku
 app: stormy-bayou-50411
 api_key: ${HEROKU_API_KEY}
